In [2]:
import pandas as pd

idades = [19, 24, 31, 18, 27, 22, 35, 29, 21, 40, 17, 26, 33, 23, 30]

series = pd.Series(idades)
series

0     19
1     24
2     31
3     18
4     27
5     22
6     35
7     29
8     21
9     40
10    17
11    26
12    33
13    23
14    30
dtype: int64

In [3]:
series.sum()

np.int64(395)

In [5]:

series.min()

17

In [6]:
series.max()

40

In [7]:
series.mean()

np.float64(26.333333333333332)

In [10]:
series.describe()

count    15.000000
mean     26.333333
std       6.672616
min      17.000000
25%      21.500000
50%      26.000000
75%      30.500000
max      40.000000
dtype: float64

In [11]:
clientes = pd.read_csv("../../data/clientes.csv", sep=";")
clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [15]:
clientes["flTwitch"].sum()
clientes["flTwitch"].mean()

np.float64(0.7284282133906194)

In [17]:
redes_socias = ["flEmail","flTwitch","flYouTube","flBlueSky","flInstagram"]
clientes[redes_socias].mean()

flEmail        0.072503
flTwitch       0.728428
flYouTube      0.056570
flBlueSky      0.000000
flInstagram    0.000000
dtype: float64

In [18]:
clientes[redes_socias].describe()

           flEmail     flTwitch   flYouTube  flBlueSky  flInstagram
count  5586.000000  5586.000000  5586.00000     5586.0       5586.0
mean      0.072503     0.728428     0.05657        0.0          0.0
std       0.259342     0.444810     0.23104        0.0          0.0
min       0.000000     0.000000     0.00000        0.0          0.0
25%       0.000000     0.000000     0.00000        0.0          0.0
50%       0.000000     1.000000     0.00000        0.0          0.0
75%       0.000000     1.000000     0.00000        0.0          0.0
max       1.000000     1.000000     1.00000        0.0          0.0