In [1]:
import pandas as pd 

df = pd.DataFrame({
    "cliente": [1,2,3,4,5],
    "nome": ["teo", "jose", "nah", "mah", "lah"],
})

df_02 = pd.DataFrame({
    "cliente": [6,7,8],
    "nome": ["kozato", "laura", "dan",],
    "idade":[32,29,31],
})

df_03 = pd.DataFrame({
    "idade": [32,34,19,54,33]
})

In [2]:
# Concat serve para empilhar data frames
# Ignore index reseta o index
dfs = [df, df_02]
pd.concat(dfs, ignore_index=True)

   cliente    nome  idade
0        1     teo    NaN
1        2    jose    NaN
2        3     nah    NaN
3        4     mah    NaN
4        5     lah    NaN
5        6  kozato   32.0
6        7   laura   29.0
7        8     dan   31.0

In [5]:
# Tambem pode cocatena um no lado do outro ( Praticamente um Join, mas sem foreign key, so usando a ordem da linhas)
# o Drop = True serve para que nao armazene o indexs antigos, se deixar o default False o index antes do sort vai ficar salvo em uma coluna
df_03 = df_03.sort_values(by=["idade"]).reset_index(drop=True)

new_df = pd.concat([df, df_03], axis=1)
new_df.head(5)

   cliente  nome  idade
0        1   teo     19
1        2  jose     32
2        3   nah     33
3        4   mah     34
4        5   lah     54