In [1]:
import pandas as pd

df = pd.read_csv("../../data/clientes.csv", sep=";")
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [ ]:
# Para remover todos os NA ( NA = Null aqui)
# Tem criterios how

df.dropna()
df.dropna(how="all") # a linha inteira tem que ser na para remover
# O padrão é any, se tiver qualquer campo da linha for na vai remover a linha toda

In [3]:
df_exemplo = pd.DataFrame({
    "nome" : ["Teo", None, "Nah", "Marcio"],
    "idade" : [None, None, 43, 52],
    "salario" : [3553, 4235, None, 5312]
})

In [4]:
# Para remover Na especifico de alguma coluna usa-se subset com uma lista com o nome do campo(s)
df_exemplo.dropna(how="any", subset=["salario"])

     nome  idade  salario
0     Teo    NaN   3553.0
1    None    NaN   4235.0
3  Marcio   52.0   5312.0

In [7]:
# Para preencher valores Na usa o fillna

df_exemplo.fillna(0) # Ou posso fillna na coluna 
df_exemplo["idade"].fillna(0)

0     0.0
1     0.0
2    43.0
3    52.0
Name: idade, dtype: float64

In [9]:
medidas = df_exemplo[["idade", "salario"]].mean()
type(medidas)

pandas.core.series.Series