In [1]:
import pandas as pd

df = pd.read_csv("../../data/clientes.csv", sep=";")
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [11]:
exemplo = pd.DataFrame({
    "nome": ["teo", "lara", "nah", "bia", "mah", "lara", "mah", "mah"],
    "sobrenome" : ["calvo", "calvo", "ataide", "ataide", "silva", "silva", "silva", "silva"],
    "salario" : [1234, 5312, 5221, 2345, 1233, 6643, 4783, 6533]
})

exemplo.head()

   nome sobrenome  salario
0   teo     calvo     1234
1  lara     calvo     5312
2   nah    ataide     5221
3   bia    ataide     2345
4   mah     silva     1233

In [ ]:
# Vai remover as linhas que são totalmente iguais ( Linha repetida ) - Por padrão so vai deixar a primeira 
exemplo.drop_duplicates()
exemplo.drop_duplicates(keep="last") # Se usar keep last vai remover as primeiras iguais e deixar somente a ultima

In [12]:
# Se quiser analisar so colunas especificas com linhas duplicadas
exemplo.drop_duplicates(subset=["nome", "sobrenome"])

   nome sobrenome  salario
0   teo     calvo     1234
1  lara     calvo     5312
2   nah    ataide     5221
3   bia    ataide     2345
4   mah     silva     1233
5  lara     silva     6643