In [1]:
import pandas as pd
# O segredo para passar o que voce quer emplihar é o set index
df = pd.DataFrame({
    "atletas" : ["Matheus", "João", "Luiz", "Arthur"],
    "atletismo" : [1, 2, 2, 1],
    "futebol" : [3, 2, 1, 4],
    "volei" : [0, 1, 1, 2]
})

df.head()

   atletas  atletismo  futebol  volei
0  Matheus          1        3      0
1     João          2        2      1
2     Luiz          2        1      1
3   Arthur          1        4      2

In [2]:
# E interessante stack ( empilhar ), quando nao sabemos se tera mais colunas
# No caso poderia ter mais esportes
# Empilhando fica mais facil adcionar esportes novos, caso deixasse do outro jeito teria que crair uma nova coluna para cada novo esporte
df = df.set_index(["atletas"])
df = df.stack()
df.head()
# Isso retorna uma Series

atletas
Matheus  atletismo    1
         futebol      3
         volei        0
João     atletismo    2
         futebol      2
dtype: int64

In [3]:
# Reset index faz ser um DataFrame
df = df.reset_index()
df.columns = ["Atleta", "Esporte", "Medalhas"]
df.head()

    Atleta    Esporte  Medalhas
0  Matheus  atletismo         1
1  Matheus    futebol         3
2  Matheus      volei         0
3     João  atletismo         2
4     João    futebol         2

In [4]:
# Unstack vai desimpilhar a o df
df = df.set_index(["Atleta", "Esporte"]).unstack().reset_index()
df.head()

          Atleta  Medalhas
Esporte          atletismo futebol volei
0         Arthur         1       4     2
1           João         2       2     1
2           Luiz         2       1     1
3        Matheus         1       3     0

In [5]:
df.columns

MultiIndex([(  'Atleta',          ''),
            ('Medalhas', 'atletismo'),
            ('Medalhas',   'futebol'),
            ('Medalhas',     'volei')],
           names=[None, 'Esporte'])

In [6]:
# df.columns = ["Atleta", "Atletismo", "Futebol", "Volei"]
# df.head()

In [7]:
df = df.rename(columns={
    ("Atleta", ""): ("Atleta", ""),
    ("Medalhas", "atletismo"): ("Atletismo", ""),
    ("Medalhas", "futebol"): ("Futebol", ""),
    ("Medalhas", "volei"): ("Vôlei", "")
})
df.head()

          Atleta  Medalhas
Esporte          atletismo futebol volei
0         Arthur         1       4     2
1           João         2       2     1
2           Luiz         2       1     1
3        Matheus         1       3     0